import postgres from 'postgres';

type DatabaseClient = ReturnType<typeof postgres>;

export interface EventRow {
  id: number;
  title: string;
  body: string | null;
  location: string | null;
  starts_at: number;
  ends_at: number | null;
  facility_id: string | null;
  reservation_id: string | null;
  created_by: string;
  created_at: number;
  notified_at: number | null;
  discord_message_id: string | null;
}

export interface NewEvent {
  title: string;
  body?: string | null;
  location?: string | null;
  startsAt: number;
  endsAt?: number | null;
  facilityId?: string | null;
  reservationId?: string | null;
  createdBy: string;
}

const EVENT_COLUMNS = `
  id, title, body, location,
  (EXTRACT(EPOCH FROM starts_at) * 1000)::double precision AS starts_at,
  CASE WHEN ends_at IS NULL THEN NULL
       ELSE (EXTRACT(EPOCH FROM ends_at) * 1000)::double precision END AS ends_at,
  facility_id, reservation_id, created_by,
  (EXTRACT(EPOCH FROM created_at) * 1000)::double precision AS created_at,
  CASE WHEN notified_at IS NULL THEN NULL
       ELSE (EXTRACT(EPOCH FROM notified_at) * 1000)::double precision END AS notified_at,
  discord_message_id
`;

export class EventStore {
  constructor(private readonly sql: DatabaseClient) {}

  async initialize(): Promise<void> {
    await this.sql`
      CREATE TABLE IF NOT EXISTS glab_event (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        body TEXT,
        location TEXT,
        starts_at TIMESTAMPTZ NOT NULL,
        ends_at TIMESTAMPTZ,
        facility_id TEXT,
        reservation_id TEXT,
        created_by TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        notified_at TIMESTAMPTZ,
        discord_message_id TEXT
      )
    `;
    await this.sql`CREATE INDEX IF NOT EXISTS glab_event_starts ON glab_event(starts_at)`;
  }

  async create(event: NewEvent): Promise<number> {
    const [created] = await this.sql<{ id: number }[]>`
      INSERT INTO glab_event
        (title, body, location, starts_at, ends_at, facility_id, reservation_id, created_by)
      VALUES (
        ${event.title}, ${event.body ?? null}, ${event.location ?? null},
        ${new Date(event.startsAt)}, ${event.endsAt == null ? null : new Date(event.endsAt)},
        ${event.facilityId ?? null}, ${event.reservationId ?? null}, ${event.createdBy}
      )
      RETURNING id
    `;
    if (!created) throw new Error('failed to create GLAB event');
    return created.id;
  }

  async list(includePast = false): Promise<EventRow[]> {
    const rows = includePast
      ? await this.sql.unsafe(`SELECT ${EVENT_COLUMNS} FROM glab_event ORDER BY starts_at DESC`)
      : await this.sql.unsafe(
        `SELECT ${EVENT_COLUMNS} FROM glab_event WHERE starts_at >= $1 ORDER BY starts_at ASC`,
        [new Date()],
      );
    return rows as unknown as EventRow[];
  }

  async get(id: number): Promise<EventRow | null> {
    const rows = await this.sql.unsafe(
      `SELECT ${EVENT_COLUMNS} FROM glab_event WHERE id = $1`,
      [id],
    );
    return (rows[0] as unknown as EventRow | undefined) ?? null;
  }

  async delete(id: number): Promise<boolean> {
    const rows = await this.sql<{ id: number }[]>`
      DELETE FROM glab_event WHERE id = ${id} RETURNING id
    `;
    return rows.length > 0;
  }

  async markNotified(id: number, discordMessageId: string | null): Promise<void> {
    await this.sql`
      UPDATE glab_event
      SET notified_at = NOW(), discord_message_id = ${discordMessageId}
      WHERE id = ${id}
    `;
  }

  async dueForReminder(windowMs: number): Promise<EventRow[]> {
    const rows = await this.sql.unsafe(
      `SELECT ${EVENT_COLUMNS}
       FROM glab_event
       WHERE notified_at IS NULL AND starts_at >= $1 AND starts_at <= $2
       ORDER BY starts_at ASC`,
      [new Date(), new Date(Date.now() + windowMs)],
    );
    return rows as unknown as EventRow[];
  }

  async findActive(now = Date.now()): Promise<EventRow | null> {
    const at = new Date(now);
    const rows = await this.sql.unsafe(
      `SELECT ${EVENT_COLUMNS}
       FROM glab_event
       WHERE starts_at <= $1 AND ends_at IS NOT NULL AND ends_at > $1
       ORDER BY starts_at DESC LIMIT 1`,
      [at],
    );
    return (rows[0] as unknown as EventRow | undefined) ?? null;
  }

  async close(): Promise<void> {
    await this.sql.end({ timeout: 5 });
  }
}

let eventStore: EventStore | null = null;

export async function initializeEventStore(databaseUrl: string | undefined): Promise<EventStore> {
  if (eventStore) return eventStore;
  const normalized = databaseUrl?.trim();
  if (!normalized) throw new Error('GLAB_DATABASE_URL is required');
  const url = new URL(normalized);
  if (url.protocol !== 'postgres:' && url.protocol !== 'postgresql:') {
    throw new Error('GLAB_DATABASE_URL must use postgres:// or postgresql://');
  }
  const store = new EventStore(postgres(normalized, { max: 5 }));
  try {
    await store.initialize();
  } catch (error) {
    await store.close().catch(() => undefined);
    throw error;
  }
  eventStore = store;
  return store;
}

export function getEventStore(): EventStore {
  if (!eventStore) throw new Error('GLAB event store has not been initialized');
  return eventStore;
}

export async function closeEventStore(): Promise<void> {
  const store = eventStore;
  eventStore = null;
  if (store) await store.close();
}
